#!/bin/bash 
unzip twitter-data-zip_/tweets.04.11.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.11.2016.json.zip twitter-data-zip/tweets.04.11.2016.json
rm twitter-data-zip/tweets.04.11.2016.json

unzip twitter-data-zip_/tweets.04.12.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.12.2016.json.zip twitter-data-zip/tweets.04.12.2016.json
rm twitter-data-zip/tweets.04.12.2016.json

unzip twitter-data-zip_/tweets.04.13.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.13.2016.json.zip twitter-data-zip/tweets.04.13.2016.json
rm twitter-data-zip/tweets.04.13.2016.json

unzip twitter-data-zip_/tweets.04.14.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.14.2016.json.zip twitter-data-zip/tweets.04.14.2016.json
rm twitter-data-zip/tweets.04.14.2016.json

unzip twitter-data-zip_/tweets.04.15.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.15.2016.json.zip twitter-data-zip/tweets.04.15.2016.json
rm twitter-data-zip/tweets.04.15.2016.json

unzip twitter-data-zip_/tweets.04.16.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.16.2016.json.zip twitter-data-zip/tweets.04.16.2016.json
rm twitter-data-zip/tweets.04.16.2016.json

unzip twitter-data-zip_/tweets.04.17.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.17.2016.json.zip twitter-data-zip/tweets.04.17.2016.json
rm twitter-data-zip/tweets.04.17.2016.json

unzip twitter-data-zip_/tweets.04.18.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.18.2016.json.zip twitter-data-zip/tweets.04.18.2016.json
rm twitter-data-zip/tweets.04.18.2016.json

unzip twitter-data-zip_/tweets.04.19.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.19.2016.json.zip twitter-data-zip/tweets.04.19.2016.json
rm twitter-data-zip/tweets.04.19.2016.json

unzip twitter-data-zip_/tweets.04.20.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.20.2016.json.zip twitter-data-zip/tweets.04.20.2016.json
rm twitter-data-zip/tweets.04.20.2016.json

unzip twitter-data-zip_/tweets.04.21.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.21.2016.json.zip twitter-data-zip/tweets.04.21.2016.json
rm twitter-data-zip/tweets.04.21.2016.json

unzip twitter-data-zip_/tweets.04.22.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.22.2016.json.zip twitter-data-zip/tweets.04.22.2016.json
rm twitter-data-zip/tweets.04.22.2016.json

unzip twitter-data-zip_/tweets.04.23.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.23.2016.json.zip twitter-data-zip/tweets.04.23.2016.json
rm twitter-data-zip/tweets.04.23.2016.json

unzip twitter-data-zip_/tweets.04.24.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.24.2016.json.zip twitter-data-zip/tweets.04.24.2016.json
rm twitter-data-zip/tweets.04.24.2016.json

unzip twitter-data-zip_/tweets.04.25.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.25.2016.json.zip twitter-data-zip/tweets.04.25.2016.json
rm twitter-data-zip/tweets.04.25.2016.json

unzip twitter-data-zip_/tweets.04.26.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.26.2016.json.zip twitter-data-zip/tweets.04.26.2016.json
rm twitter-data-zip/tweets.04.26.2016.json

unzip twitter-data-zip_/tweets.04.27.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.27.2016.json.zip twitter-data-zip/tweets.04.27.2016.json
rm twitter-data-zip/tweets.04.27.2016.json

unzip twitter-data-zip_/tweets.04.28.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.28.2016.json.zip twitter-data-zip/tweets.04.28.2016.json
rm twitter-data-zip/tweets.04.28.2016.json

unzip twitter-data-zip_/tweets.04.29.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.29.2016.json.zip twitter-data-zip/tweets.04.29.2016.json
rm twitter-data-zip/tweets.04.29.2016.json

unzip twitter-data-zip_/tweets.04.30.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.04.30.2016.json.zip twitter-data-zip/tweets.04.30.2016.json
rm twitter-data-zip/tweets.04.30.2016.json

unzip twitter-data-zip_/tweets.05.01.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.01.2016.json.zip twitter-data-zip/tweets.05.01.2016.json
rm twitter-data-zip/tweets.05.01.2016.json

unzip twitter-data-zip_/tweets.05.02.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.02.2016.json.zip twitter-data-zip/tweets.05.02.2016.json
rm twitter-data-zip/tweets.05.02.2016.json

unzip twitter-data-zip_/tweets.05.03.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.03.2016.json.zip twitter-data-zip/tweets.05.03.2016.json
rm twitter-data-zip/tweets.05.03.2016.json

unzip twitter-data-zip_/tweets.05.04.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.04.2016.json.zip twitter-data-zip/tweets.05.04.2016.json
rm twitter-data-zip/tweets.05.04.2016.json

unzip twitter-data-zip_/tweets.05.05.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.05.2016.json.zip twitter-data-zip/tweets.05.05.2016.json
rm twitter-data-zip/tweets.05.05.2016.json

unzip twitter-data-zip_/tweets.05.06.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.06.2016.json.zip twitter-data-zip/tweets.05.06.2016.json
rm twitter-data-zip/tweets.05.06.2016.json

unzip twitter-data-zip_/tweets.05.07.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.07.2016.json.zip twitter-data-zip/tweets.05.07.2016.json
rm twitter-data-zip/tweets.05.07.2016.json

unzip twitter-data-zip_/tweets.05.08.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.08.2016.json.zip twitter-data-zip/tweets.05.08.2016.json
rm twitter-data-zip/tweets.05.08.2016.json

unzip twitter-data-zip_/tweets.05.09.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.09.2016.json.zip twitter-data-zip/tweets.05.09.2016.json
rm twitter-data-zip/tweets.05.09.2016.json

unzip twitter-data-zip_/tweets.05.10.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.10.2016.json.zip twitter-data-zip/tweets.05.10.2016.json
rm twitter-data-zip/tweets.05.10.2016.json

unzip twitter-data-zip_/tweets.05.12.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.12.2016.json.zip twitter-data-zip/tweets.05.12.2016.json
rm twitter-data-zip/tweets.05.12.2016.json

unzip twitter-data-zip_/tweets.05.13.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.13.2016.json.zip twitter-data-zip/tweets.05.13.2016.json
rm twitter-data-zip/tweets.05.13.2016.json

unzip twitter-data-zip_/tweets.05.14.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.14.2016.json.zip twitter-data-zip/tweets.05.14.2016.json
rm twitter-data-zip/tweets.05.14.2016.json

unzip twitter-data-zip_/tweets.05.15.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.15.2016.json.zip twitter-data-zip/tweets.05.15.2016.json
rm twitter-data-zip/tweets.05.15.2016.json

unzip twitter-data-zip_/tweets.05.16.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.16.2016.json.zip twitter-data-zip/tweets.05.16.2016.json
rm twitter-data-zip/tweets.05.16.2016.json

unzip twitter-data-zip_/tweets.05.17.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.17.2016.json.zip twitter-data-zip/tweets.05.17.2016.json
rm twitter-data-zip/tweets.05.17.2016.json

unzip twitter-data-zip_/tweets.05.18.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.18.2016.json.zip twitter-data-zip/tweets.05.18.2016.json
rm twitter-data-zip/tweets.05.18.2016.json

unzip twitter-data-zip_/tweets.05.19.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.19.2016.json.zip twitter-data-zip/tweets.05.19.2016.json
rm twitter-data-zip/tweets.05.19.2016.json

unzip twitter-data-zip_/tweets.05.20.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.20.2016.json.zip twitter-data-zip/tweets.05.20.2016.json
rm twitter-data-zip/tweets.05.20.2016.json

unzip twitter-data-zip_/tweets.05.21.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.21.2016.json.zip twitter-data-zip/tweets.05.21.2016.json
rm twitter-data-zip/tweets.05.21.2016.json

unzip twitter-data-zip_/tweets.05.22.2016.json.zip -d twitter-data-zip 
zip -j twitter-data-zip/tweets.05.22.2016.json.zip twitter-data-zip/tweets.05.22.2016.json
rm twitter-data-zip/tweets.05.22.2016.json


